import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {motion,useScroll,useTransform} from 'framer-motion';
import {ArrowUpRight,ChevronDown,Menu,X,Scale,ShieldCheck,Globe2,Building2,MapPin,Phone,Mail,Clock,CheckCircle2} from 'lucide-react';
import './styles.css';

const practices=[
 {icon:Globe2,title:'Immigration Law',text:'Strategic guidance for Canadian immigration matters, applications, status and pathways.'},
 {icon:ShieldCheck,title:'Criminal Law',text:'Focused representation built around preparation, advocacy and protecting your rights.'},
 {icon:Building2,title:'Real Estate Law',text:'Practical legal support for residential and commercial real estate transactions.'}
];
const fade={hidden:{opacity:0,y:30},show:{opacity:1,y:0,transition:{duration:.7,ease:[.22,1,.36,1]}}};
function App(){
 const [open,setOpen]=useState(false); const [active,setActive]=useState(null); const {scrollYProgress}=useScroll(); const scale=useTransform(scrollYProgress,[0,1],[1,1.14]);
 useEffect(()=>{document.querySelectorAll('a[href^="#"]').forEach(a=>a.onclick=()=>setOpen(false))},[]);
 return <div className="app">
  <div className="grain"/>
  <header className="nav"><a className="brand" href="#top"><span className="crest"><Scale size={18}/></span><span><b>KANWARPAL</b><small>SINGH THAKUR</small></span></a><nav className={open?'open':''}><a href="#about">About</a><a href="#practice">Practice Areas</a><a href="#approach">Approach</a><a href="#contact">Contact</a></nav><a className="navCta" href="#contact">Book a Consultation <ArrowUpRight size={16}/></a><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>
  <main id="top">
   <section className="hero"><motion.div style={{scale}} className="heroGlow"/><div className="heroGrid"/><div className="heroContent"><motion.div initial="hidden" animate="show" variants={fade}><span className="eyebrow">BARRISTER & SOLICITOR · VAUGHAN, ONTARIO</span><h1>Clear counsel.<br/><em>Confident representation.</em></h1><p>Experienced legal guidance across immigration, criminal and real estate matters—with a client-first approach built on clarity and trust.</p><div className="heroBtns"><a className="primary" href="#contact">Schedule a Consultation <ArrowUpRight size={17}/></a><a className="secondary" href="#practice">Explore Practice Areas <ChevronDown size={17}/></a></div></motion.div><motion.div className="heroStamp" initial={{opacity:0,scale:.8}} animate={{opacity:1,scale:1}} transition={{delay:.7,duration:.7}}><div>⚖</div><span>JUSTICE<br/>INTEGRITY<br/>ADVOCACY</span></motion.div></div><div className="scroll">SCROLL TO EXPLORE <span/></div></section>
   <section className="intro" id="about"><div className="container two"><motion.div initial="hidden" whileInView="show" viewport={{once:true}} variants={fade}><span className="eyebrow gold">A MODERN APPROACH TO LAW</span><h2>Legal advice should feel <em>clear, not complicated.</em></h2></motion.div><motion.div initial="hidden" whileInView="show" viewport={{once:true}} variants={fade}><p className="lead">KanwarPal Singh Thakur provides thoughtful, practical legal representation for individuals, families and businesses in Vaughan and across Ontario.</p><p>Every matter deserves attention to detail, straightforward communication and a strategy tailored to the people behind the file.</p><a className="textLink" href="#contact">Start a conversation <ArrowUpRight size={16}/></a></motion.div></div></section>
   <section className="practice" id="practice"><div className="container"><div className="sectionHead"><div><span className="eyebrow gold">WHAT WE DO</span><h2>Practice <em>areas.</em></h2></div><p>Focused legal services with a disciplined, personal approach.</p></div><div className="cards">{practices.map((p,i)=>{let I=p.icon;return <motion.article className="card" key={p.title} initial="hidden" whileInView="show" viewport={{once:true}} variants={fade} transition={{delay:i*.12}} onClick={()=>setActive(active===i?null:i)}><div className="cardTop"><span className="num">0{i+1}</span><I size={27}/></div><h3>{p.title}</h3><p>{p.text}</p><span className="cardArrow"><ArrowUpRight size={20}/></span>{active===i&&<motion.div className="cardMore" initial={{opacity:0}} animate={{opacity:1}}>Contact the office to discuss your matter and next steps.</motion.div>}</motion.article>})}</div></div></section>
   <section className="statement" id="approach"><div className="container statementInner"><motion.div initial={{opacity:0,x:-30}} whileInView={{opacity:1,x:0}} viewport={{once:true}}><span className="eyebrow">THE THAKUR APPROACH</span><h2>Precision in preparation.<br/><em>Purpose in advocacy.</em></h2></motion.div><div className="principles"><div><b>01</b><span>Listen first</span><p>Understand the facts, priorities and outcome that matter to you.</p></div><div><b>02</b><span>Build the strategy</span><p>Translate complexity into a practical, focused legal plan.</p></div><div><b>03</b><span>Move with purpose</span><p>Keep communication clear while pursuing the strongest path forward.</p></div></div></div></section>
   <section className="location"><div className="container locationBox"><div><span className="eyebrow gold">THE OFFICE</span><h2>Vaughan, <em>Ontario.</em></h2><p><MapPin size={17}/> 81 Zenway Blvd, Unit 2<br/>Vaughan, Ontario L4H 0S5</p></div><div className="mapArt"><div className="mapPin"><MapPin/></div><div className="rings r1"/><div className="rings r2"/><span>VAUGHAN</span></div></div></section>
   <section className="contact" id="contact"><div className="container contactGrid"><div><span className="eyebrow gold">LET'S TALK</span><h2>Your matter deserves<br/><em>focused attention.</em></h2><p>Reach out to schedule a consultation and take the next step with clarity.</p><div className="contactDetails"><a href="tel:+19055550100"><Phone size={17}/> Office consultation line</a><a href="mailto:office@example.com"><Mail size={17}/> Email the office</a><span><Clock size={17}/> By appointment</span></div></div><form onSubmit={e=>{e.preventDefault();alert('Thank you. Please connect this form to your preferred email service.')}}><label>Full Name<input required placeholder="Your name"/></label><label>Email<input required type="email" placeholder="you@example.com"/></label><label>How can we help?<select><option>Immigration Law</option><option>Criminal Law</option><option>Real Estate Law</option><option>General Consultation</option></select></label><label>Message<textarea rows="4" placeholder="Tell us briefly about your matter..."/></label><button className="primary" type="submit">Request Consultation <ArrowUpRight size={17}/></button><small>Information submitted through this form is for initial contact only and does not create a lawyer-client relationship.</small></form></div></section>
  </main><footer><div className="container footerTop"><div className="brand"><span className="crest"><Scale size={18}/></span><span><b>KANWARPAL</b><small>SINGH THAKUR</small></span></div><p>Posts are not legal advice.</p><div><a href="#top">Back to top ↑</a></div></div><div className="container copyright">© {new Date().getFullYear()} KanwarPal Singh Thakur. All rights reserved.</div></footer>
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
